from pathlib import Path

PATH_ASSETS = Path("./randomdungeon/assets")
PATH_GRAPHICS = PATH_ASSETS / "graphics"
PATH_GRAPHICS_TILES = PATH_GRAPHICS / "tiles"

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
FPS = 60

BACKGROUND_COLOR = "palegreen2"

HERO_COLOR = "white"
HERO_RADIUS = 10.0
HERO_SPEED = 200

ROOM_TILE_RADIUS = 20
