from pathlib import Path

PATH_ASSETS = Path("./randomdungeon/assets")

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
FPS = 60

BACKGROUND_COLOR = "palegreen2"
TILE_RADIUS = 25

CHARACTER_DISTANCE_TO_TILE_EPSILON = 2.0

HERO_TILE_FILE_IDX = "0099"
HERO_SPEED = 200

GRAPHICS_PATH = PATH_ASSETS / "graphics"
GRAPHICS_TILES_PATH = GRAPHICS_PATH / "tiles"

MUSIC_PATH = PATH_ASSETS / "music"

DEBUG_RENDER_STATS = True
DEBUG_RENDER_TILE_BORDERS = True
DEBUG_RENDER_GAME_MAP = True
DEBUG_RENDER_HERO_TILES = True
