from pathlib import Path

import pygame

PATH_ASSETS = Path("./randomdungeon/assets")

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
FPS = 60

BACKGROUND_COLOR = "palegreen2"
MENU_COLOR = "aquamarine4"

TILE_RADIUS = 25

CHARACTER_DISTANCE_TO_TILE_EPSILON = 2.0

HERO_TILE_FILE_IDX = "0099"
HERO_SPEED = 200
HERO_ATTACK_COUNTDOWN_IN_SECS = 0.5
HERO_ATTACK_DURATION_IN_SECS = 2.0
HERO_ATTACK_DISTANCE = 60

WEAPON_TILE_FILE_IDX = "0125"
WEAPON_POSITION_DELTA = pygame.Vector2(30, 0)
WEAPON_IDLE_ANGLE_IN_DEGREES = -15.0

FIREBALL_TILE_FILE_IDX = "0132"
FIREBALL_SPEED = 300
FIREBALL_ROTATION_SPEED = 500

LASER_TILE_FILE_IDX = "0133"
LASER_SPEED = 300

HEART_TILE_FILE_IDX = "0134"

MONSTER_CRAB_TILE_FILE_IDX = "0110"

GRAPHICS_PATH = PATH_ASSETS / "graphics"
GRAPHICS_TILES_PATH = GRAPHICS_PATH / "tiles"

AUDIO_PATH = PATH_ASSETS / "audio"
AUDIO_MUSIC_PATH = AUDIO_PATH / "music"
AUDIO_EFFECTS_PATH = AUDIO_PATH / "effects"

DEBUG_RENDER_STATS = False
DEBUG_RENDER_TILE_BORDERS = False
DEBUG_RENDER_GAME_MAP = False
DEBUG_RENDER_CHARACTER_TILES = False
DEBUG_RENDER_COLLISION_BOX = False
